openapi: 3.0.2
info:
  title: Authorization
  description: >-
    Mittels dieser API erhalten Sie, basierend auf den von Prohyp zur Verf&uuml;gung
    gestellten Authorisierungsdaten, einen Access Token für weitere
    Schnittstellenaufrufe.
  version: v1
  termsOfService: "http://prohyp.de"
  contact:
    name: Prohyp GmbH / Accountmanagement
    url: http://www.prohyp.de
    email: AM@prohyp.de
  x-logo:
    url: "https://www.prohyp.de/prohyp-assets/images/logo-svg.svg?1508412251"
    backgroundColor: "#FFFFFF"
    altText: "Prohyp logo"
servers:
  - url: 'https://ppapi-test.azure-api.net/authorization/v1'
paths:
  /protocol/openid-connect/token:
    post:
      tags:
        - authorization
      summary: Access Token abrufen
      description: >
        Um einen Access Token zu erhalten, muss der Client die
        Authorisierungsdaten übermitteln.  
        Weitere Informationen finden Sie hier: 
        https://tools.ietf.org/html/rfc6749#section-4.
      operationId: request_access_token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRequest'
            example: >-
              grant_type=password&client_id=client_id&client_secret=client_secret&username=user&password=password
      responses:
        '200':
          description: Erfolgreicher Aufruf mit Access Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Fehlerhafte Anfrage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthProblem'
        '401':
          description: Authentifizierung fehlgeschlagen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthProblem'          
        '403':
          description: Zugriff verweigert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthProblem'          
        '404':
          description: Nicht gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthProblem'          
        '500':
          description: Interner Server Fehler
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthProblem'          
components:
  schemas:
    OAuthProblem:
      description: Fehler bei der Authentifizierung
      properties:
        error:
          type: string
          description: Fehlermeldung
          example: invalid_token
        error_description:
          type: string
          description: Weitere Beschreibung des Fehlerbildes
          example: Access token expired  
    TokenRequest:
      required:
        - grant_type
        - client_id
      properties:
        grant_type:
          type: string
          description: Aufruftyp
        client_id:
          type: string
          description: Client ID des aufrufenden Clients
        client_secret:
          type: string
          format: password
          description: Client Secret des aufrufenden Clients
        username:
          type: string
          description: Benutzername des aufrufenden Benutzers
        password:
          type: string
          format: password
          description: Passwort des aufrufenden Benutzers
    TokenResponse:
      description: Rückmeldung mit Access Token bei gültigem Aufruf
      required:
        - access_token
        - scope
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          description: 'Der Access Token, der von Interhyp ausgestellt wurde'
          example: 2YotnFZFEjr1zCsicMWpAA
        expires_in:
          type: integer
          description: Gültigkeit des Access Tokens in Sekunden
          format: int64
          example: 60
        refresh_expires_in:
          type: integer
          description: Gültigkeit des Refresh Tokens in Sekunden
          format: int64
          example: 60
        refresh_token:
          type: string
          description: >
            Mit dem Request Token kann nach Ablauf des Access Tokens ein neuer
            Token abgerufen werden
          example: tGzv3JOkF0XG5Qx2TlKWIA
        token_type:
          type: string
          description: Der Typ des Access Tokens
          example: Bearer
        scope:
          type: string
          description: >
            Zugewiesene Bereiche, optional  

            Weitere Informationen finden Sie hier:
            https://tools.ietf.org/html/rfc6749#section-3.3
          example: read write
